apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lp-metrics-exporter
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch
