apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lb-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lp-metrics-exporter
subjects:
- kind: ServiceAccount
  name: exporter
  namespace: sisyphus