apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lp-exporter
  name: lp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lp-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lp-exporter
    spec:
      serviceAccountName: lp-metrics-exporter
      containers:
      - image: python:3.7
        name: python
        env:
          # If pushgateway helm release name is different from "pushgateway"
          # then you should specify pushgateway address as an environment variable
          - name: PUSHGATEWAY_URL 
            value: "192.168.0.24:32457"
          # If storage class name is different from "local-path" then you 
          # should rename it here
          - name: STORAGE_CLASS_NAME
            value: "local-path"
          # Default Log Level is INFO
          - name: LOG_LEVEL
            value: "INFO"