apiVersion: batch/v1
kind: Job
metadata:
  name: lp-exporter-job-NODES
  labels:
    exporter: lp-exporter-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        exporter: lp-exporter
    spec:
      containers:
      - name: job
        image: ugurozturk99/lp-exporter-job:v0.0.32-SNAPSHOT
        command: ["python3", "job.py"]
        env:
          - name: PUSHGATEWAY_ADDRESS
            value: "PGWADRESS"
          - name: PVC_NAMES
            value: "CLAIMS"
          - name: LOG_LEVEL
            value: "JOBLOGLEVEL"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - mountPath: /node
          name: nodedata
      restartPolicy: Never
      nodeName: NODES
      volumes:
      - name: nodedata
        hostPath:
          path: "VMPPATH"
  backoffLimit: 1
