apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: lp-metrics-exporter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lp-metrics-exporter
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lp-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lp-metrics-exporter
subjects:
- kind: ServiceAccount
  name: lp-metrics-exporter
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: lp-metrics-exporter
  name: secret-sa-lp-metrics-exporter
  namespace: default
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lp-exporter
    exporter: lp-exporter-deployment
  name: lp-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lp-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lp-exporter
        exporter: lp-exporter
    spec:
      serviceAccountName: lp-metrics-exporter
      containers:
      - image: ugurozturk99/lp-exporter-deployment:v0.0.31-SNAPSHOT
        name: python
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # If helm release name of pushgateway is different from "pushgateway" OR 
          # you are planning to deploy exporter to different namespace than the one 
          # that pushgateway deployed to then you have to specify pushgateway address 
          # as an environment variable
          #- name: PUSHGATEWAY_ADDRESS 
          #  value: "10.99.84.233:9091"
          # If storage class name is different from "local-path" then you 
          # should specify it here
          #- name: STORAGE_CLASS_NAME
          #  value: "local-path"
          # Default Log Level is INFO
          #- name: LOG_LEVEL
          #  value: "INFO"
          # Default Job Log Level is DEBUG
          #- name: JOB_LOG_LEVEL
          #  value: "DEBUG"
          # Default Volume Provision Path is /opt/local-path-provisioner
          #- name: VOLUMEPROVISIONPATH
          #  value: "/opt/local-path-provisioner"