name: Docker Build

on:
  push:
    branches: [ "main" ]


jobs:

  build:
    name: Build docker image and push this image to docker.io container registry
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Source Code
      uses: actions/checkout@v2
    - name: Set variables
      run: |
        VER=$(cat env | awk {'print$2'})
        echo $VER
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build for lb-exporter-deployment
      run: |
        cd src/deployment && docker build -t ugurozturk99/lp-exporter-deployment:v${{ env.VERSION }} -f Dockerfile .
        docker tag  ugurozturk99/lp-exporter-deployment:v${{ env.VERSION }} ugurozturk99/lp-exporter-deployment:latest
   # - name: Run Trivy vulnerability scanner for lb-exporter-deployment
   #   uses: aquasecurity/trivy-action@master
   #   with:
   #     image-ref: 'ugurozturk99/lp-exporter-deployment:v${{ env.VERSION }}'
   #     format: 'table'
   #     exit-code: '1'
   #     ignore-unfixed: true
   #     vuln-type: 'os,library'
   #     severity: 'CRITICAL,HIGH'
    - name: Push for lb-exporter-deployment
      run: |
        docker push ugurozturk99/lp-exporter-deployment:v${{ env.VERSION }} 
        docker push ugurozturk99/lp-exporter-deployment:latest
    - name: Build for lb-exporter-job
      run: |
        cd src/job && docker build -t ugurozturk99/lp-exporter-job:v${{ env.VERSION }} -f Dockerfile .
        docker tag  ugurozturk99/lp-exporter-job:v${{ env.VERSION }} ugurozturk99/lp-exporter-job:latest
   # - name: Run Trivy vulnerability scanner for lb-exporter-job
   #   uses: aquasecurity/trivy-action@master
   #   with:
   #     image-ref: 'ugurozturk99/lp-exporter-job:v${{ env.VERSION }}'
   #     format: 'table'
   #     exit-code: '1'
   #     ignore-unfixed: true
   #     vuln-type: 'os,library'
   #     severity: 'CRITICAL,HIGH'
    - name: Push for lb-exporter-job
      run: |
        docker push ugurozturk99/lp-exporter-job:v${{ env.VERSION }} 
        docker push ugurozturk99/lp-exporter-job:latest
